export const TAGS_ACQUIRE_FAILURE = 'TAGS_ACQUIRE_FAILURE';
export const TAGS_ACQUIRE_LOADING = 'TAGS_ACQUIRE_LOADING';
export const TAGS_ACQUIRE_SUCCESS = 'TAGS_ACQUIRE_SUCCESS';
export const TAGS_SET_PAGE_NUMBER = 'TAGS_SET_PAGE_NUMBER';
