"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NUMBER_OF_ALBUMS_TO_SHOW = exports.MONGO_DB_NAME = exports.MONGO_DB_URL = exports.MAX_RETRIES = exports.MAX_CACHE_AGE_IN_DAYS_FOR_TAG = exports.MAX_CACHE_AGE_IN_DAYS_FOR_ARTIST = exports.MAX_CACHE_AGE_IN_DAYS_FOR_ALBUM = exports.MAX_CACHE_AGE_IN_DAYS_BY_DEFAULT = exports.LASTFM_API_ERRORS = void 0;
exports.LASTFM_API_ERRORS = {
    AUTH_FAILED: 4,
    INVALID_API_KEY: 10,
    INVALID_FORMAT: 5,
    INVALID_METHOD: 3,
    INVALID_METHOD_SIGNATURE: 13,
    INVALID_PARAMETERS: 6,
    INVALID_RESOURCE: 7,
    INVALID_SERVICE: 2,
    OPERATION_FAILED: 8,
    RATE_LIMIT_EXCEEDED: 29,
    SERVICE_OFFLINE: 11,
    SUSPENDED_API_KEY: 26,
    TEMPORARY: 16,
};
exports.MAX_CACHE_AGE_IN_DAYS_BY_DEFAULT = 7;
exports.MAX_CACHE_AGE_IN_DAYS_FOR_ALBUM = 180;
exports.MAX_CACHE_AGE_IN_DAYS_FOR_ARTIST = 31;
exports.MAX_CACHE_AGE_IN_DAYS_FOR_TAG = 7;
exports.MAX_RETRIES = 3;
exports.MONGO_DB_URL = 'mongodb://localhost:27017';
exports.MONGO_DB_NAME = 'lastfm';
exports.NUMBER_OF_ALBUMS_TO_SHOW = 100;
//# sourceMappingURL=constants.js.map